### expected running time for full set: 18h
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_butyryl_fentanyl_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_butyryl_fentanyl_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_butyryl_fentanyl_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_butyryl_fentanyl_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_butyryl_fentanyl_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_butyryl_fentanyl_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_butyryl_fentanyl_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_butyryl_fentanyl_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_butyryl_fentanyl_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_butyryl_fentanyl_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_fentanyl_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_fentanyl_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_fentanyl_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_fentanyl_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_fentanyl_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_fentanyl_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_fentanyl_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_fentanyl_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_benzyl_fentanyl_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_benzyl_fentanyl_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_phenacetin_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_phenacetin_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_phenacetin_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_phenacetin_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_phenacetin_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_phenacetin_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_phenacetin_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_phenacetin_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_phenacetin_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_phenacetin_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_carfentanil_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_carfentanil_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_carfentanil_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_carfentanil_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_carfentanil_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_carfentanil_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_carfentanil_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_carfentanil_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_carfentanil_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_carfentanil_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_hcl_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_hcl_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_hcl_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_hcl_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_hcl_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_hcl_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_hcl_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_hcl_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heroin_hcl_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heroin_hcl_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_hcl_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_hcl_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_hcl_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_hcl_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_hcl_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_hcl_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_hcl_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_hcl_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cocaine_hcl_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cocaine_hcl_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_hcl_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_hcl_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_hcl_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_hcl_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_hcl_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_hcl_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_hcl_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_hcl_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_mdma_hcl_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_mdma_hcl_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lsd_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lsd_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lsd_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lsd_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lsd_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lsd_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lsd_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lsd_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lsd_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lsd_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_methamphetamine_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_methamphetamine_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_methamphetamine_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_methamphetamine_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_methamphetamine_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_methamphetamine_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_methamphetamine_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_methamphetamine_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_methamphetamine_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_methamphetamine_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_rdx_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_rdx_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_rdx_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_rdx_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_rdx_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_rdx_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_rdx_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_rdx_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_rdx_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_rdx_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petn_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petn_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petn_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petn_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petn_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petn_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petn_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petn_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petn_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petn_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tnt_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tnt_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tnt_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tnt_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tnt_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tnt_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tnt_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tnt_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tnt_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tnt_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tatp_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tatp_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tatp_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tatp_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tatp_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tatp_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tatp_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tatp_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tatp_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tatp_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nitroglycerin_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nitroglycerin_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nitroglycerin_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nitroglycerin_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nitroglycerin_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nitroglycerin_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nitroglycerin_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nitroglycerin_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nitroglycerin_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nitroglycerin_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_acetaminophen_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_acetaminophen_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_acetaminophen_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_acetaminophen_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_acetaminophen_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_acetaminophen_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_acetaminophen_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_acetaminophen_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_acetaminophen_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_acetaminophen_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_sucrose_sugar_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_sucrose_sugar_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_sucrose_sugar_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_sucrose_sugar_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_sucrose_sugar_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_sucrose_sugar_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_sucrose_sugar_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_sucrose_sugar_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_sucrose_sugar_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_sucrose_sugar_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cellulose_cotton_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cellulose_cotton_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cellulose_cotton_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cellulose_cotton_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cellulose_cotton_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cellulose_cotton_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cellulose_cotton_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cellulose_cotton_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cellulose_cotton_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cellulose_cotton_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_polyester_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_polyester_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_polyester_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_polyester_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_polyester_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_polyester_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_polyester_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_polyester_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_polyester_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_polyester_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_office_paper_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_office_paper_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_office_paper_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_office_paper_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_office_paper_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_office_paper_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_office_paper_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_office_paper_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_office_paper_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_office_paper_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cardboard_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cardboard_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cardboard_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cardboard_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cardboard_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cardboard_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cardboard_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cardboard_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_cardboard_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_cardboard_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_milk_powder_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_milk_powder_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_milk_powder_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_milk_powder_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_milk_powder_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_milk_powder_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_milk_powder_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_milk_powder_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_milk_powder_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_milk_powder_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_toothpaste_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_toothpaste_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_toothpaste_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_toothpaste_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_toothpaste_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_toothpaste_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_toothpaste_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_toothpaste_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_toothpaste_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_toothpaste_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_soap_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_soap_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_soap_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_soap_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_soap_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_soap_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_soap_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_soap_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_soap_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_soap_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_collagen_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_collagen_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_collagen_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_collagen_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_collagen_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_collagen_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_collagen_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_collagen_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_collagen_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_collagen_50g.root
