### expected running time for full set: 26.6667h
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10l90_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10l90_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10l90_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10l90_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10l90_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10l90_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10l90_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10l90_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10l90_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10l90_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20l80_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20l80_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20l80_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20l80_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20l80_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20l80_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20l80_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20l80_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20l80_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20l80_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25l75_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25l75_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25l75_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25l75_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25l75_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25l75_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25l75_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25l75_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25l75_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25l75_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35l65_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35l65_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35l65_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35l65_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35l65_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35l65_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35l65_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35l65_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35l65_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35l65_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30bs70_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30bs70_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30bs70_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30bs70_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30bs70_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30bs70_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30bs70_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30bs70_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30bs70_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30bs70_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40l60_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40l60_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10bs90_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10bs90_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15bs85_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15bs85_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf25bs75_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf25bs75_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35bs65_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35bs65_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35bs65_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35bs65_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35bs65_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35bs65_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35bs65_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35bs65_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35bs65_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35bs65_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45bs55_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45bs55_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45bs55_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45bs55_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45bs55_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45bs55_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45bs55_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45bs55_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45bs55_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45bs55_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf50bs50_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf50bs50_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf50bs50_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf50bs50_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf50bs50_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf50bs50_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf50bs50_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf50bs50_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf50bs50_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf50bs50_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05a95_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05a95_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05a95_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05a95_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05a95_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05a95_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05a95_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05a95_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05a95_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05a95_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10a90_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10a90_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10a90_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10a90_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10a90_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10a90_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10a90_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10a90_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf10a90_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf10a90_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15a85_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15a85_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15a85_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15a85_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15a85_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15a85_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15a85_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15a85_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15a85_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15a85_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30a70_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30a70_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30a70_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30a70_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30a70_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30a70_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30a70_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30a70_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf30a70_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf30a70_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40a60_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40a60_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40a60_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40a60_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40a60_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40a60_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40a60_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40a60_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf40a60_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf40a60_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45a55_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45a55_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45a55_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45a55_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45a55_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45a55_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45a55_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45a55_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45a55_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45a55_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10l90_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10l90_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10l90_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10l90_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10l90_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10l90_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10l90_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10l90_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10l90_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10l90_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15l85_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15l85_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15l85_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15l85_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15l85_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15l85_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15l85_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15l85_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15l85_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15l85_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25l75_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25l75_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25l75_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25l75_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25l75_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25l75_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25l75_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25l75_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25l75_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25l75_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35l65_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35l65_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35l65_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35l65_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35l65_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35l65_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35l65_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35l65_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35l65_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35l65_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40l60_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40l60_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40l60_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40l60_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40l60_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40l60_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40l60_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40l60_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40l60_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40l60_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05bs95_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05bs95_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05bs95_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05bs95_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05bs95_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05bs95_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05bs95_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05bs95_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05bs95_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05bs95_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10bs90_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10bs90_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10bs90_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10bs90_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10bs90_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10bs90_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10bs90_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10bs90_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10bs90_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10bs90_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25bs75_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25bs75_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25bs75_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25bs75_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25bs75_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25bs75_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25bs75_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25bs75_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25bs75_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25bs75_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf30bs70_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf30bs70_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf30bs70_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf30bs70_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf30bs70_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf30bs70_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf30bs70_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf30bs70_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf30bs70_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf30bs70_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35bs65_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35bs65_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35bs65_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35bs65_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35bs65_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35bs65_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35bs65_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35bs65_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35bs65_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35bs65_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40bs60_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40bs60_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40bs60_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40bs60_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40bs60_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40bs60_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40bs60_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40bs60_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40bs60_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40bs60_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45bs55_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45bs55_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45bs55_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45bs55_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45bs55_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45bs55_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45bs55_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45bs55_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45bs55_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45bs55_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15a85_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15a85_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15a85_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15a85_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15a85_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15a85_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15a85_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15a85_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15a85_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15a85_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25a75_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25a75_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25a75_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25a75_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25a75_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25a75_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25a75_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25a75_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf25a75_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf25a75_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35a65_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35a65_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35a65_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35a65_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35a65_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35a65_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35a65_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35a65_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf35a65_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf35a65_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf50a50_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf50a50_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf50a50_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf50a50_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf50a50_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf50a50_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf50a50_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf50a50_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf50a50_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf50a50_50g.root
