### expected running time for full set: 6.66667h
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15l85_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15l85_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15l85_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15l85_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15l85_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15l85_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15l85_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15l85_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf15l85_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf15l85_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf45l55_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf45l55_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf05bs95_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf05bs95_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20bs80_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20bs80_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20bs80_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20bs80_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20bs80_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20bs80_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20bs80_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20bs80_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf20bs80_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf20bs80_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35a65_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35a65_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35a65_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35a65_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35a65_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35a65_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35a65_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35a65_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bbf35a65_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bbf35a65_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05l95_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05l95_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05l95_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05l95_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05l95_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05l95_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05l95_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05l95_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf05l95_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf05l95_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45l55_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45l55_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45l55_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45l55_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45l55_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45l55_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45l55_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45l55_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf45l55_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf45l55_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15bs85_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15bs85_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15bs85_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15bs85_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15bs85_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15bs85_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15bs85_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15bs85_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf15bs85_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf15bs85_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10a90_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10a90_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10a90_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10a90_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10a90_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10a90_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10a90_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10a90_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf10a90_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf10a90_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40a60_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40a60_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40a60_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40a60_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40a60_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40a60_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40a60_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40a60_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_bf40a60_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_bf40a60_50g.root
