### expected running time for full set: 11.3333h
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_oxycodone_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_oxycodone_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_oxycodone_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_oxycodone_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_oxycodone_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_oxycodone_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_oxycodone_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_oxycodone_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_oxycodone_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_oxycodone_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_hcl_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_hcl_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_hcl_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_hcl_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_hcl_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_hcl_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_hcl_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_hcl_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_u47700_hcl_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_u47700_hcl_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_na_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_na_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_na_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_na_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_na_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_na_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_na_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_na_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ghb_na_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ghb_na_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_dihydrocodeine_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_dihydrocodeine_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_dihydrocodeine_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_dihydrocodeine_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_dihydrocodeine_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_dihydrocodeine_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_dihydrocodeine_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_dihydrocodeine_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_dihydrocodeine_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_dihydrocodeine_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tapentadol_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tapentadol_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tapentadol_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tapentadol_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tapentadol_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tapentadol_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tapentadol_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tapentadol_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tapentadol_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tapentadol_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tramadol_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tramadol_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tramadol_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tramadol_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tramadol_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tramadol_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tramadol_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tramadol_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tramadol_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tramadol_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_stanazolol_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_stanazolol_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_stanazolol_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_stanazolol_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_stanazolol_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_stanazolol_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_stanazolol_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_stanazolol_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_stanazolol_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_stanazolol_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_trenbolone_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_trenbolone_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_trenbolone_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_trenbolone_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_trenbolone_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_trenbolone_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_trenbolone_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_trenbolone_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_trenbolone_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_trenbolone_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ambien_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ambien_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ambien_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ambien_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ambien_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ambien_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ambien_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ambien_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_ambien_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_ambien_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_armodafinil_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_armodafinil_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_armodafinil_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_armodafinil_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_armodafinil_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_armodafinil_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_armodafinil_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_armodafinil_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_armodafinil_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_armodafinil_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clonazepam_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clonazepam_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clonazepam_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clonazepam_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clonazepam_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clonazepam_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clonazepam_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clonazepam_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clonazepam_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clonazepam_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escitalopram_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escitalopram_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escitalopram_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escitalopram_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escitalopram_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escitalopram_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escitalopram_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escitalopram_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escitalopram_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escitalopram_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escoparone_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escoparone_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escoparone_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escoparone_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escoparone_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escoparone_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escoparone_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escoparone_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_escoparone_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_escoparone_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tizanidine_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tizanidine_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tizanidine_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tizanidine_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tizanidine_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tizanidine_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tizanidine_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tizanidine_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_tizanidine_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_tizanidine_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clenbuterol_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clenbuterol_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clenbuterol_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clenbuterol_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clenbuterol_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clenbuterol_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clenbuterol_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clenbuterol_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_clenbuterol_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_clenbuterol_50g.root
