### expected running time for full set: 4h
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petrol_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petrol_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petrol_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petrol_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petrol_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petrol_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petrol_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petrol_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_petrol_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_petrol_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_aspirin_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_aspirin_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_aspirin_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_aspirin_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_aspirin_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_aspirin_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_aspirin_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_aspirin_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_aspirin_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_aspirin_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heamoglobin_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heamoglobin_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heamoglobin_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heamoglobin_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heamoglobin_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heamoglobin_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heamoglobin_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heamoglobin_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_heamoglobin_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_heamoglobin_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nicotine_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nicotine_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nicotine_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nicotine_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nicotine_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nicotine_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nicotine_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nicotine_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_nicotine_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_nicotine_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_epsomsalts_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_epsomsalts_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_epsomsalts_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_epsomsalts_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_epsomsalts_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_epsomsalts_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_epsomsalts_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_epsomsalts_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_epsomsalts_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_epsomsalts_50g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lactose_1000g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lactose_1000g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lactose_500g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lactose_500g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lactose_200g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lactose_200g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lactose_100g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lactose_100g.root
/home/dynaxion-rt/software/allpix-squared/bin/allpix -c /home/dynaxion-rt/software/parcel/parcelsForChallenge/configs/simulation_g4_lactose_50g.conf
mv /home/dynaxion-rt/software/parcel/parcelsForChallenge/output/modules.root /home/dynaxion-rt/simulation/output/loop-challenge/pure/material_g4_lactose_50g.root
